# Generated by Django 6.0 on 2025-12-08 19:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('date_created', models.DateTimeField(default=datetime.datetime(2025, 12, 8, 19, 20, 16, 68612, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
