# Generated by Django 6.0 on 2026-01-12 18:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_userfeedback_article_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='approver_users',
            field=models.ManyToManyField(related_name='articles_to_approve', to=settings.AUTH_USER_MODEL),
        ),
    ]
