# Generated by Django 6.0 on 2026-01-12 19:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_article_approver_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='watched_users',
            field=models.ManyToManyField(related_name='watched_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
